services:
  app:
    build: .
    container_name: spring-secure-identity
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=${MYSQL_ROOT_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - API_SECURITY_TOKEN_SECRET=${JWT_SECRET}

      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_CREATE=${ADMIN_CREATE}

      - APP_FRONTEND_URL_LOCAL=${APP_FRONTEND_URL_LOCAL}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: spring-secure-identity-db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10